-- Comprehensive Customer Database Schema for MySQL with UTF-8 encoding
USE customer_db;

-- Set character set for session
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = utf8mb4_unicode_ci;

-- Customers table - main customer information
CREATE TABLE IF NOT EXISTS customers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(25),
    MOBILE VARCHAR(25),
    DATE_OF_BIRTH DATE,
    GENDER ENUM('Male', 'Female', 'Other', 'Prefer not to say') DEFAULT 'Prefer not to say',
    REGISTRATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN DATETIME,
    STATUS ENUM('Active', 'Inactive', 'Suspended', 'Pending') DEFAULT 'Active',
    CUSTOMER_TYPE ENUM('Individual', 'Business', 'Enterprise', 'VIP') DEFAULT 'Individual',
    PREFERRED_LANGUAGE VARCHAR(5) DEFAULT 'en',
    TIMEZONE VARCHAR(50) DEFAULT 'UTC',
    AVATAR_URL VARCHAR(255),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_CUSTOMER_CODE (CUSTOMER_CODE),
    INDEX IDX_REGISTRATION_DATE (REGISTRATION_DATE),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_CUSTOMER_TYPE (CUSTOMER_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Companies table - business customer information
CREATE TABLE IF NOT EXISTS companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    LEGAL_NAME VARCHAR(200),
    REGISTRATION_NUMBER VARCHAR(50),
    TAX_NUMBER VARCHAR(50),
    INDUSTRY VARCHAR(100),
    COMPANY_SIZE ENUM('Startup', 'Small', 'Medium', 'Large', 'Enterprise') DEFAULT 'Small',
    WEBSITE VARCHAR(255),
    FOUNDED_YEAR YEAR,
    DESCRIPTION TEXT,
    ANNUAL_REVENUE DECIMAL(15,2),
    EMPLOYEE_COUNT INT,
    LOGO_URL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_COMPANY_NAME (COMPANY_NAME),
    INDEX IDX_INDUSTRY (INDUSTRY),
    INDEX IDX_COMPANY_SIZE (COMPANY_SIZE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customer company relationships
CREATE TABLE IF NOT EXISTS customer_companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    POSITION VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (COMPANY_ID) REFERENCES companies(ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_CUSTOMER_COMPANY (CUSTOMER_ID, COMPANY_ID),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_COMPANY_ID (COMPANY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Addresses table
CREATE TABLE IF NOT EXISTS addresses (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ADDRESS_TYPE ENUM('Home', 'Work', 'Billing', 'Shipping', 'Other') DEFAULT 'Home',
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    APARTMENT VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_ADDRESS_TYPE (ADDRESS_TYPE),
    INDEX IDX_COUNTRY (COUNTRY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Communication preferences
CREATE TABLE IF NOT EXISTS communication_preferences (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    EMAIL_MARKETING BOOLEAN DEFAULT TRUE,
    SMS_MARKETING BOOLEAN DEFAULT FALSE,
    PHONE_CALLS BOOLEAN DEFAULT FALSE,
    PREFERRED_CONTACT_METHOD ENUM('Email', 'Phone', 'SMS', 'Mail') DEFAULT 'Email',
    CONTACT_FREQUENCY ENUM('Daily', 'Weekly', 'Monthly', 'Quarterly', 'Never') DEFAULT 'Weekly',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products table
CREATE TABLE IF NOT EXISTS products (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10, 2) NOT NULL,
    SKU VARCHAR(100) UNIQUE NOT NULL,
    STOCK_QUANTITY INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled') DEFAULT 'Pending',
    TOTAL_AMOUNT DECIMAL(10, 2),
    SHIPPING_ADDRESS_ID INT,
    BILLING_ADDRESS_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES addresses(ID) ON DELETE SET NULL,
    FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES addresses(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Leads table
CREATE TABLE IF NOT EXISTS leads (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(25),
    COMPANY_NAME VARCHAR(200),
    STATUS ENUM('New', 'Contacted', 'Qualified', 'Disqualified', 'Converted') DEFAULT 'New',
    SOURCE VARCHAR(100),
    ASSIGNED_TO INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES customers(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DUE_DATE DATE,
    PRIORITY ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT 'Medium',
    STATUS ENUM('Not Started', 'In Progress', 'Completed', 'Deferred') DEFAULT 'Not Started',
    ASSIGNED_TO INT,
    RELATED_TO_TYPE VARCHAR(50),
    RELATED_TO_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES customers(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deals table
CREATE TABLE IF NOT EXISTS deals (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEAL_NAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT,
    CONTACT_PERSON_ID INT,
    AMOUNT DECIMAL(12, 2),
    STAGE ENUM('Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost') DEFAULT 'Prospecting',
    CLOSE_DATE DATE,
    ASSIGNED_TO INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES companies(ID) ON DELETE SET NULL,
    FOREIGN KEY (CONTACT_PERSON_ID) REFERENCES customers(ID) ON DELETE SET NULL,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES customers(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Invoices table
CREATE TABLE IF NOT EXISTS invoices (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10, 2),
    STATUS ENUM('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled') DEFAULT 'Draft',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deliveries table
CREATE TABLE IF NOT EXISTS deliveries (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    SHIPPING_DATE DATE,
    DELIVERY_DATE DATE,
    CARRIER VARCHAR(100),
    TRACKING_NUMBER VARCHAR(100),
    STATUS ENUM('Preparing', 'Shipped', 'In Transit', 'Delivered', 'Failed') DEFAULT 'Preparing',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Additional CRM and Business Tables

-- Sales pipeline stages
CREATE TABLE IF NOT EXISTS sales_stages (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STAGE_NAME VARCHAR(100) NOT NULL,
    STAGE_ORDER INT NOT NULL,
    PROBABILITY DECIMAL(5,2) DEFAULT 0,
    IS_CLOSED BOOLEAN DEFAULT FALSE,
    IS_WON BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_STAGE_ORDER (STAGE_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product categories
CREATE TABLE IF NOT EXISTS product_categories (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(150) NOT NULL,
    PARENT_CATEGORY_ID INT NULL,
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    SORT_ORDER INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES product_categories(ID) ON DELETE SET NULL,
    INDEX IDX_CATEGORY_NAME (CATEGORY_NAME),
    INDEX IDX_PARENT_CATEGORY (PARENT_CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Suppliers
CREATE TABLE IF NOT EXISTS suppliers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(200) NOT NULL,
    CONTACT_PERSON VARCHAR(150),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(25),
    ADDRESS TEXT,
    PAYMENT_TERMS VARCHAR(100),
    DELIVERY_TIME_DAYS INT DEFAULT 0,
    RATING DECIMAL(3,2) DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_SUPPLIER_NAME (SUPPLIER_NAME),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inventory management
CREATE TABLE IF NOT EXISTS inventory (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    WAREHOUSE_LOCATION VARCHAR(100),
    QUANTITY_ON_HAND INT DEFAULT 0,
    QUANTITY_RESERVED INT DEFAULT 0,
    QUANTITY_AVAILABLE INT GENERATED ALWAYS AS (QUANTITY_ON_HAND - QUANTITY_RESERVED) STORED,
    MIN_STOCK_LEVEL INT DEFAULT 0,
    MAX_STOCK_LEVEL INT DEFAULT 0,
    LAST_COUNT_DATE DATE,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID) ON DELETE CASCADE,
    INDEX IDX_PRODUCT_ID (PRODUCT_ID),
    INDEX IDX_WAREHOUSE_LOCATION (WAREHOUSE_LOCATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customer interactions history
CREATE TABLE IF NOT EXISTS customer_interactions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    INTERACTION_TYPE ENUM('Call', 'Email', 'Meeting', 'Support', 'Sale', 'Marketing', 'Follow-up') NOT NULL,
    SUBJECT VARCHAR(255),
    DESCRIPTION TEXT,
    INTERACTION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DURATION_MINUTES INT DEFAULT 0,
    OUTCOME ENUM('Positive', 'Negative', 'Neutral', 'Follow-up Required') DEFAULT 'Neutral',
    NEXT_ACTION VARCHAR(255),
    NEXT_ACTION_DATE DATE,
    ASSIGNED_TO INT,
    CREATED_BY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES customers(ID) ON DELETE SET NULL,
    FOREIGN KEY (CREATED_BY) REFERENCES customers(ID) ON DELETE SET NULL,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_INTERACTION_TYPE (INTERACTION_TYPE),
    INDEX IDX_INTERACTION_DATE (INTERACTION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Support tickets
CREATE TABLE IF NOT EXISTS support_tickets (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TICKET_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIORITY ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT 'Medium',
    STATUS ENUM('Open', 'In Progress', 'Waiting Customer', 'Resolved', 'Closed') DEFAULT 'Open',
    CATEGORY VARCHAR(100),
    ASSIGNED_TO INT,
    CREATED_BY INT,
    RESOLUTION TEXT,
    RESOLVED_AT DATETIME NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES customers(ID) ON DELETE SET NULL,
    FOREIGN KEY (CREATED_BY) REFERENCES customers(ID) ON DELETE SET NULL,
    INDEX IDX_TICKET_NUMBER (TICKET_NUMBER),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_PRIORITY (PRIORITY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Payment methods
CREATE TABLE IF NOT EXISTS payment_methods (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    METHOD_TYPE ENUM('Credit Card', 'Debit Card', 'Bank Transfer', 'PayPal', 'Cryptocurrency') NOT NULL,
    PROVIDER VARCHAR(100),
    ACCOUNT_NUMBER VARCHAR(100),
    EXPIRY_DATE DATE,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_METHOD_TYPE (METHOD_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Payments
CREATE TABLE IF NOT EXISTS payments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PAYMENT_METHOD_ID INT,
    AMOUNT DECIMAL(12,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    PAYMENT_STATUS ENUM('Pending', 'Processing', 'Completed', 'Failed', 'Refunded') DEFAULT 'Pending',
    TRANSACTION_ID VARCHAR(255),
    GATEWAY_RESPONSE TEXT,
    PROCESSED_AT DATETIME NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES payment_methods(ID) ON DELETE SET NULL,
    INDEX IDX_ORDER_ID (ORDER_ID),
    INDEX IDX_PAYMENT_STATUS (PAYMENT_STATUS),
    INDEX IDX_TRANSACTION_ID (TRANSACTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Discounts and promotions
CREATE TABLE IF NOT EXISTS promotions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PROMOTION_NAME VARCHAR(200) NOT NULL,
    PROMOTION_CODE VARCHAR(50) UNIQUE,
    DISCOUNT_TYPE ENUM('Percentage', 'Fixed Amount', 'Free Shipping') NOT NULL,
    DISCOUNT_VALUE DECIMAL(10,2) NOT NULL,
    MIN_ORDER_AMOUNT DECIMAL(10,2) DEFAULT 0,
    MAX_DISCOUNT_AMOUNT DECIMAL(10,2),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    USAGE_LIMIT INT,
    USAGE_COUNT INT DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_PROMOTION_CODE (PROMOTION_CODE),
    INDEX IDX_START_END_DATE (START_DATE, END_DATE),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Order promotions usage
CREATE TABLE IF NOT EXISTS order_promotions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PROMOTION_ID INT NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10,2) NOT NULL,
    APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (PROMOTION_ID) REFERENCES promotions(ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_ORDER_PROMOTION (ORDER_ID, PROMOTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Marketing campaigns
CREATE TABLE IF NOT EXISTS marketing_campaigns (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR(200) NOT NULL,
    CAMPAIGN_TYPE ENUM('Email', 'SMS', 'Social Media', 'Print', 'TV', 'Radio', 'Online Ads') NOT NULL,
    DESCRIPTION TEXT,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    BUDGET DECIMAL(12,2),
    TARGET_AUDIENCE TEXT,
    EXPECTED_REACH INT,
    ACTUAL_REACH INT DEFAULT 0,
    CONVERSIONS INT DEFAULT 0,
    ROI DECIMAL(8,4),
    STATUS ENUM('Planning', 'Active', 'Paused', 'Completed', 'Cancelled') DEFAULT 'Planning',
    CREATED_BY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES customers(ID) ON DELETE SET NULL,
    INDEX IDX_CAMPAIGN_TYPE (CAMPAIGN_TYPE),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_START_END_DATE (START_DATE, END_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Reviews and ratings
CREATE TABLE IF NOT EXISTS product_reviews (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    ORDER_ID INT,
    RATING DECIMAL(2,1) NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
    REVIEW_TITLE VARCHAR(200),
    REVIEW_TEXT TEXT,
    IS_VERIFIED_PURCHASE BOOLEAN DEFAULT FALSE,
    IS_APPROVED BOOLEAN DEFAULT FALSE,
    HELPFUL_VOTES INT DEFAULT 0,
    TOTAL_VOTES INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE SET NULL,
    INDEX IDX_PRODUCT_ID (PRODUCT_ID),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_RATING (RATING)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

