-- Comprehensive Customer Database Schema for MySQL with UTF-8 encoding
USE customer_db;

-- Set character set for session
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = utf8mb4_unicode_ci;

-- Customers table - main customer information
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(25),
    MOBILE VARCHAR(25),
    DATE_OF_BIRTH DATE,
    GENDER ENUM('Male', 'Female', 'Other', 'Prefer not to say') DEFAULT 'Prefer not to say',
    REGISTRATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN DATETIME,
    STATUS ENUM('Active', 'Inactive', 'Suspended', 'Pending') DEFAULT 'Active',
    CUSTOMER_TYPE ENUM('Individual', 'Business', 'Enterprise', 'VIP') DEFAULT 'Individual',
    PREFERRED_LANGUAGE VARCHAR(5) DEFAULT 'en',
    TIMEZONE VARCHAR(50) DEFAULT 'UTC',
    AVATAR_URL VARCHAR(255),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_CUSTOMER_CODE (CUSTOMER_CODE),
    INDEX IDX_REGISTRATION_DATE (REGISTRATION_DATE),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_CUSTOMER_TYPE (CUSTOMER_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Companies table - business customer information
CREATE TABLE IF NOT EXISTS COMPANIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    LEGAL_NAME VARCHAR(200),
    REGISTRATION_NUMBER VARCHAR(50),
    TAX_NUMBER VARCHAR(50),
    INDUSTRY VARCHAR(100),
    COMPANY_SIZE ENUM('Startup', 'Small', 'Medium', 'Large', 'Enterprise') DEFAULT 'Small',
    WEBSITE VARCHAR(255),
    FOUNDED_YEAR YEAR,
    DESCRIPTION TEXT,
    ANNUAL_REVENUE DECIMAL(15,2),
    EMPLOYEE_COUNT INT,
    LOGO_URL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_COMPANY_NAME (COMPANY_NAME),
    INDEX IDX_INDUSTRY (INDUSTRY),
    INDEX IDX_COMPANY_SIZE (COMPANY_SIZE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customer company relationships
CREATE TABLE IF NOT EXISTS CUSTOMER_COMPANIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    POSITION VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_CUSTOMER_COMPANY (CUSTOMER_ID, COMPANY_ID),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_COMPANY_ID (COMPANY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Addresses table
CREATE TABLE IF NOT EXISTS ADDRESSES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ADDRESS_TYPE ENUM('Home', 'Work', 'Billing', 'Shipping', 'Other') DEFAULT 'Home',
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    APARTMENT VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_ADDRESS_TYPE (ADDRESS_TYPE),
    INDEX IDX_COUNTRY (COUNTRY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Communication preferences
CREATE TABLE IF NOT EXISTS COMMUNICATION_PREFERENCES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    EMAIL_MARKETING BOOLEAN DEFAULT TRUE,
    SMS_MARKETING BOOLEAN DEFAULT FALSE,
    PHONE_CALLS BOOLEAN DEFAULT FALSE,
    PREFERRED_CONTACT_METHOD ENUM('Email', 'Phone', 'SMS', 'Mail') DEFAULT 'Email',
    CONTACT_FREQUENCY ENUM('Daily', 'Weekly', 'Monthly', 'Quarterly', 'Never') DEFAULT 'Weekly',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products table
CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10, 2) NOT NULL,
    SKU VARCHAR(100) UNIQUE NOT NULL,
    STOCK_QUANTITY INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Orders table
CREATE TABLE IF NOT EXISTS ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled') DEFAULT 'Pending',
    TOTAL_AMOUNT DECIMAL(10, 2),
    SHIPPING_ADDRESS_ID INT,
    BILLING_ADDRESS_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES ADDRESSES(ID) ON DELETE SET NULL,
    FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES ADDRESSES(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Order Items table
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Leads table
CREATE TABLE IF NOT EXISTS LEADS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(25),
    COMPANY_NAME VARCHAR(200),
    STATUS ENUM('New', 'Contacted', 'Qualified', 'Disqualified', 'Converted') DEFAULT 'New',
    SOURCE VARCHAR(100),
    ASSIGNED_TO INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES CUSTOMERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tasks table
CREATE TABLE IF NOT EXISTS TASKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DUE_DATE DATE,
    PRIORITY ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT 'Medium',
    STATUS ENUM('Not Started', 'In Progress', 'Completed', 'Deferred') DEFAULT 'Not Started',
    ASSIGNED_TO INT,
    RELATED_TO_TYPE VARCHAR(50),
    RELATED_TO_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES CUSTOMERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deals table
CREATE TABLE IF NOT EXISTS DEALS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEAL_NAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT,
    CONTACT_PERSON_ID INT,
    AMOUNT DECIMAL(12, 2),
    STAGE ENUM('Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost') DEFAULT 'Prospecting',
    CLOSE_DATE DATE,
    ASSIGNED_TO INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE SET NULL,
    FOREIGN KEY (CONTACT_PERSON_ID) REFERENCES CUSTOMERS(ID) ON DELETE SET NULL,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES CUSTOMERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Invoices table
CREATE TABLE IF NOT EXISTS INVOICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10, 2),
    STATUS ENUM('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled') DEFAULT 'Draft',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deliveries table
CREATE TABLE IF NOT EXISTS DELIVERIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    SHIPPING_DATE DATE,
    DELIVERY_DATE DATE,
    CARRIER VARCHAR(100),
    TRACKING_NUMBER VARCHAR(100),
    STATUS ENUM('Preparing', 'Shipped', 'In Transit', 'Delivered', 'Failed') DEFAULT 'Preparing',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
