-- Comprehensive Customer Database Schema for MySQL with UTF-8 encoding
USE customer_db;

-- Set character set for session
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = utf8mb4_unicode_ci;

-- Customers table - main customer information
CREATE TABLE IF NOT EXISTS customers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(25),
    MOBILE VARCHAR(25),
    DATE_OF_BIRTH DATE,
    GENDER ENUM('Male', 'Female', 'Other', 'Prefer not to say') DEFAULT 'Prefer not to say',
    REGISTRATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN DATETIME,
    STATUS ENUM('Active', 'Inactive', 'Suspended', 'Pending') DEFAULT 'Active',
    CUSTOMER_TYPE ENUM('Individual', 'Business', 'Enterprise', 'VIP') DEFAULT 'Individual',
    PREFERRED_LANGUAGE VARCHAR(5) DEFAULT 'en',
    TIMEZONE VARCHAR(50) DEFAULT 'UTC',
    AVATAR_URL VARCHAR(255),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_CUSTOMER_CODE (CUSTOMER_CODE),
    INDEX IDX_REGISTRATION_DATE (REGISTRATION_DATE),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_CUSTOMER_TYPE (CUSTOMER_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Companies table - business customer information
CREATE TABLE IF NOT EXISTS companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    LEGAL_NAME VARCHAR(200),
    REGISTRATION_NUMBER VARCHAR(50),
    TAX_NUMBER VARCHAR(50),
    INDUSTRY VARCHAR(100),
    COMPANY_SIZE ENUM('Startup', 'Small', 'Medium', 'Large', 'Enterprise') DEFAULT 'Small',
    WEBSITE VARCHAR(255),
    FOUNDED_YEAR YEAR,
    DESCRIPTION TEXT,
    ANNUAL_REVENUE DECIMAL(15,2),
    EMPLOYEE_COUNT INT,
    LOGO_URL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_COMPANY_NAME (COMPANY_NAME),
    INDEX IDX_INDUSTRY (INDUSTRY),
    INDEX IDX_COMPANY_SIZE (COMPANY_SIZE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customer-Company relationships
CREATE TABLE IF NOT EXISTS customer_companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    ROLE VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (COMPANY_ID) REFERENCES companies(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_COMPANY_ID (COMPANY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Addresses table
CREATE TABLE IF NOT EXISTS addresses (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    COMPANY_ID INT,
    ADDRESS_TYPE ENUM('Home', 'Work', 'Billing', 'Shipping', 'Other') DEFAULT 'Other',
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    APARTMENT VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'Russia',
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (COMPANY_ID) REFERENCES companies(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_COMPANY_ID (COMPANY_ID),
    INDEX IDX_ADDRESS_TYPE (ADDRESS_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products table
CREATE TABLE IF NOT EXISTS products (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_CODE VARCHAR(50) UNIQUE NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE DECIMAL(10, 2) NOT NULL,
    COST DECIMAL(10, 2),
    WEIGHT DECIMAL(8, 3),
    DIMENSIONS VARCHAR(100),
    COLOR VARCHAR(50),
    SIZE VARCHAR(50),
    MATERIAL VARCHAR(100),
    STOCK_QUANTITY INT DEFAULT 0,
    MIN_STOCK_LEVEL INT DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IMAGE_URL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_PRODUCT_CODE (PRODUCT_CODE),
    INDEX IDX_CATEGORY (CATEGORY),
    INDEX IDX_BRAND (BRAND),
    INDEX IDX_ACTIVE (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded') DEFAULT 'Pending',
    PAYMENT_METHOD ENUM('Credit Card', 'Debit Card', 'PayPal', 'Bank Transfer', 'Cash', 'Crypto') DEFAULT 'Credit Card',
    PAYMENT_STATUS ENUM('Pending', 'Paid', 'Failed', 'Refunded', 'Partially Refunded') DEFAULT 'Pending',
    SUBTOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    SHIPPING_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    DISCOUNT_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(3) DEFAULT 'RUB',
    SHIPPING_ADDRESS_ID INT,
    BILLING_ADDRESS_ID INT,
    NOTES TEXT,
    TRACKING_NUMBER VARCHAR(100),
    SHIPPED_DATE DATETIME,
    DELIVERED_DATE DATETIME,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE RESTRICT,
    FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES addresses(ID) ON DELETE SET NULL,
    FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES addresses(ID) ON DELETE SET NULL,
    INDEX IDX_ORDER_NUMBER (ORDER_NUMBER),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_ORDER_DATE (ORDER_DATE),
    INDEX IDX_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    TOTAL_PRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID) ON DELETE RESTRICT,
    INDEX IDX_ORDER_ID (ORDER_ID),
    INDEX IDX_PRODUCT_ID (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Leads table
CREATE TABLE IF NOT EXISTS leads (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LEAD_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    COMPANY_NAME VARCHAR(200),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(25),
    SOURCE VARCHAR(100),
    STATUS ENUM('New', 'Contacted', 'Qualified', 'Disqualified', 'Converted') DEFAULT 'New',
    SCORE INT DEFAULT 0,
    ASSIGNED_TO VARCHAR(100),
    NOTES TEXT,
    CONVERSION_DATE DATETIME,
    CONVERTED_CUSTOMER_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CONVERTED_CUSTOMER_ID) REFERENCES customers(ID) ON DELETE SET NULL,
    INDEX IDX_LEAD_CODE (LEAD_CODE),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_ASSIGNED_TO (ASSIGNED_TO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deals table
CREATE TABLE IF NOT EXISTS deals (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEAL_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_ID INT,
    LEAD_ID INT,
    STAGE ENUM('Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost') DEFAULT 'Prospecting',
    VALUE DECIMAL(12, 2) DEFAULT 0.00,
    CURRENCY VARCHAR(3) DEFAULT 'RUB',
    PROBABILITY INT DEFAULT 50,
    EXPECTED_CLOSE_DATE DATE,
    ACTUAL_CLOSE_DATE DATE,
    ASSIGNED_TO VARCHAR(100),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE SET NULL,
    FOREIGN KEY (LEAD_ID) REFERENCES leads(ID) ON DELETE SET NULL,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_STAGE (STAGE),
    INDEX IDX_ASSIGNED_TO (ASSIGNED_TO),
    INDEX IDX_EXPECTED_CLOSE_DATE (EXPECTED_CLOSE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    CUSTOMER_ID INT,
    LEAD_ID INT,
    DEAL_ID INT,
    ASSIGNED_TO VARCHAR(100),
    STATUS ENUM('Not Started', 'In Progress', 'Completed', 'Deferred') DEFAULT 'Not Started',
    PRIORITY ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT 'Medium',
    DUE_DATE DATETIME,
    COMPLETED_DATE DATETIME,
    ESTIMATED_HOURS DECIMAL(5, 2),
    ACTUAL_HOURS DECIMAL(5, 2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE SET NULL,
    FOREIGN KEY (LEAD_ID) REFERENCES leads(ID) ON DELETE SET NULL,
    FOREIGN KEY (DEAL_ID) REFERENCES deals(ID) ON DELETE SET NULL,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_ASSIGNED_TO (ASSIGNED_TO),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_DUE_DATE (DUE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Invoices table
CREATE TABLE IF NOT EXISTS invoices (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    ORDER_ID INT,
    DEAL_ID INT,
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS ENUM('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled') DEFAULT 'Draft',
    SUBTOTAL DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    TAX_RATE DECIMAL(5, 2) DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(12, 2) DEFAULT 0.00,
    DISCOUNT_AMOUNT DECIMAL(12, 2) DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(3) DEFAULT 'RUB',
    NOTES TEXT,
    PAYMENT_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE RESTRICT,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE SET NULL,
    FOREIGN KEY (DEAL_ID) REFERENCES deals(ID) ON DELETE SET NULL,
    INDEX IDX_INVOICE_NUMBER (INVOICE_NUMBER),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_DUE_DATE (DUE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deliveries table
CREATE TABLE IF NOT EXISTS deliveries (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DELIVERY_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    ORDER_ID INT NOT NULL,
    CARRIER VARCHAR(100),
    TRACKING_NUMBER VARCHAR(100),
    STATUS ENUM('Preparing', 'Shipped', 'In Transit', 'Delivered', 'Failed') DEFAULT 'Preparing',
    SHIPPING_DATE DATETIME,
    EXPECTED_DELIVERY_DATE DATETIME,
    ACTUAL_DELIVERY_DATE DATETIME,
    DELIVERY_ADDRESS_ID INT,
    RECIPIENT_NAME VARCHAR(200),
    RECIPIENT_PHONE VARCHAR(25),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE RESTRICT,
    FOREIGN KEY (DELIVERY_ADDRESS_ID) REFERENCES addresses(ID) ON DELETE SET NULL,
    INDEX IDX_DELIVERY_NUMBER (DELIVERY_NUMBER),
    INDEX IDX_ORDER_ID (ORDER_ID),
    INDEX IDX_TRACKING_NUMBER (TRACKING_NUMBER),
    INDEX IDX_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Support Tickets table
CREATE TABLE IF NOT EXISTS support_tickets (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TICKET_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    SUBJECT VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    PRIORITY ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT 'Medium',
    STATUS ENUM('Open', 'In Progress', 'Resolved', 'Closed', 'Reopened') DEFAULT 'Open',
    CATEGORY VARCHAR(100),
    ASSIGNED_TO VARCHAR(100),
    RESOLUTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    RESOLVED_AT DATETIME,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE RESTRICT,
    INDEX IDX_TICKET_NUMBER (TICKET_NUMBER),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_PRIORITY (PRIORITY),
    INDEX IDX_ASSIGNED_TO (ASSIGNED_TO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
