-- Comprehensive Customer Database Schema for PostgreSQL with UTF-8 encoding
-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Set database encoding to UTF8
SET client_encoding = 'UTF8';

-- Custom data types
CREATE TYPE CUSTOMER_STATUS_TYPE AS ENUM ('Active', 'Inactive', 'Suspended', 'Pending');
CREATE TYPE CUSTOMER_TYPE_ENUM AS ENUM ('Individual', 'Business', 'Enterprise', 'VIP');
CREATE TYPE GENDER_TYPE AS ENUM ('Male', 'Female', 'Other', 'Prefer not to say');
CREATE TYPE ADDRESS_TYPE AS ENUM ('Home', 'Work', 'Billing', 'Shipping', 'Other');
CREATE TYPE CONTACT_METHOD_TYPE AS ENUM ('Email', 'Phone', 'SMS', 'Mail');
CREATE TYPE CONTACT_FREQUENCY_TYPE AS ENUM ('Daily', 'Weekly', 'Monthly', 'Quarterly', 'Never');
CREATE TYPE COMPANY_SIZE_TYPE AS ENUM ('Startup', 'Small', 'Medium', 'Large', 'Enterprise');
CREATE TYPE ORDER_STATUS_TYPE AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded');
CREATE TYPE PAYMENT_METHOD_TYPE AS ENUM ('Credit Card', 'Debit Card', 'PayPal', 'Bank Transfer', 'Cash', 'Crypto');
CREATE TYPE PAYMENT_STATUS_TYPE AS ENUM ('Pending', 'Paid', 'Failed', 'Refunded', 'Partially Refunded');
CREATE TYPE INTERACTION_TYPE AS ENUM ('Email', 'Phone', 'Meeting', 'Chat', 'Support', 'Sale', 'Marketing', 'Other');
CREATE TYPE OUTCOME_TYPE AS ENUM ('Positive', 'Negative', 'Neutral', 'Follow-up Required');
CREATE TYPE PRIORITY_TYPE AS ENUM ('Low', 'Medium', 'High', 'Critical');
CREATE TYPE TICKET_STATUS_TYPE AS ENUM ('Open', 'In Progress', 'Resolved', 'Closed', 'Reopened');
CREATE TYPE DEAL_STAGE_TYPE AS ENUM ('Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost');
CREATE TYPE INVOICE_STATUS_TYPE AS ENUM ('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled');
CREATE TYPE DELIVERY_STATUS_TYPE AS ENUM ('Preparing', 'Shipped', 'In Transit', 'Delivered', 'Failed');
CREATE TYPE LEAD_STATUS_TYPE AS ENUM ('New', 'Contacted', 'Qualified', 'Disqualified', 'Converted');
CREATE TYPE TASK_STATUS_TYPE AS ENUM ('Not Started', 'In Progress', 'Completed', 'Deferred');
CREATE TYPE DISCOUNT_TYPE AS ENUM ('Percentage', 'Fixed Amount', 'Free Shipping');
CREATE TYPE CAMPAIGN_TYPE AS ENUM ('Email', 'SMS', 'Social Media', 'Print', 'TV', 'Radio', 'Online Ads');
CREATE TYPE CAMPAIGN_STATUS_TYPE AS ENUM ('Planning', 'Active', 'Paused', 'Completed', 'Cancelled');

-- Customers table - main customer information
CREATE TABLE IF NOT EXISTS customers (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(25),
    MOBILE VARCHAR(25),
    DATE_OF_BIRTH DATE,
    GENDER GENDER_TYPE DEFAULT 'Prefer not to say',
    REGISTRATION_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP WITH TIME ZONE,
    STATUS CUSTOMER_STATUS_TYPE DEFAULT 'Active',
    CUSTOMER_TYPE CUSTOMER_TYPE_ENUM DEFAULT 'Individual',
    PREFERRED_LANGUAGE VARCHAR(5) DEFAULT 'en',
    TIMEZONE VARCHAR(50) DEFAULT 'UTC',
    AVATAR_URL VARCHAR(255),
    NOTES TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_customers_EMAIL ON customers(EMAIL);
CREATE INDEX IDX_customers_CUSTOMER_CODE ON customers(CUSTOMER_CODE);
CREATE INDEX IDX_customers_REGISTRATION_DATE ON customers(REGISTRATION_DATE);
CREATE INDEX IDX_customers_STATUS ON customers(STATUS);
CREATE INDEX IDX_customers_CUSTOMER_TYPE ON customers(CUSTOMER_TYPE);

-- Companies table - business customer information
CREATE TABLE IF NOT EXISTS companies (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    COMPANY_NAME VARCHAR(200) NOT NULL,
    LEGAL_NAME VARCHAR(200),
    REGISTRATION_NUMBER VARCHAR(50),
    TAX_NUMBER VARCHAR(50),
    INDUSTRY VARCHAR(100),
    COMPANY_SIZE COMPANY_SIZE_TYPE DEFAULT 'Small',
    WEBSITE VARCHAR(255),
    FOUNDED_YEAR INTEGER,
    DESCRIPTION TEXT,
    ANNUAL_REVENUE DECIMAL(15,2),
    EMPLOYEE_COUNT INTEGER,
    LOGO_URL VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_companies_COMPANY_NAME ON companies(COMPANY_NAME);
CREATE INDEX IDX_companies_INDUSTRY ON companies(INDUSTRY);
CREATE INDEX IDX_companies_COMPANY_SIZE ON companies(COMPANY_SIZE);

-- Customer-Company relationships
CREATE TABLE IF NOT EXISTS customer_companies (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID UUID NOT NULL REFERENCES customers(ID) ON DELETE CASCADE,
    COMPANY_ID UUID NOT NULL REFERENCES companies(ID) ON DELETE CASCADE,
    ROLE VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_customer_companies_CUSTOMER_ID ON customer_companies(CUSTOMER_ID);
CREATE INDEX IDX_customer_companies_COMPANY_ID ON customer_companies(COMPANY_ID);

-- Addresses table
CREATE TABLE IF NOT EXISTS addresses (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID UUID REFERENCES customers(ID) ON DELETE CASCADE,
    COMPANY_ID UUID REFERENCES companies(ID) ON DELETE CASCADE,
    ADDRESS_TYPE ADDRESS_TYPE DEFAULT 'Other',
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    APARTMENT VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'Russia',
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_addresses_CUSTOMER_ID ON addresses(CUSTOMER_ID);
CREATE INDEX IDX_addresses_COMPANY_ID ON addresses(COMPANY_ID);
CREATE INDEX IDX_addresses_ADDRESS_TYPE ON addresses(ADDRESS_TYPE);

-- Products table
CREATE TABLE IF NOT EXISTS products (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    PRODUCT_CODE VARCHAR(50) UNIQUE NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE DECIMAL(10, 2) NOT NULL,
    COST DECIMAL(10, 2),
    WEIGHT DECIMAL(8, 3),
    DIMENSIONS VARCHAR(100),
    COLOR VARCHAR(50),
    SIZE VARCHAR(50),
    MATERIAL VARCHAR(100),
    STOCK_QUANTITY INTEGER DEFAULT 0,
    MIN_STOCK_LEVEL INTEGER DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IMAGE_URL VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_products_PRODUCT_CODE ON products(PRODUCT_CODE);
CREATE INDEX IDX_products_CATEGORY ON products(CATEGORY);
CREATE INDEX IDX_products_BRAND ON products(BRAND);
CREATE INDEX IDX_products_IS_ACTIVE ON products(IS_ACTIVE);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ORDER_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID UUID NOT NULL REFERENCES customers(ID) ON DELETE RESTRICT,
    ORDER_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    STATUS ORDER_STATUS_TYPE DEFAULT 'Pending',
    PAYMENT_METHOD PAYMENT_METHOD_TYPE DEFAULT 'Credit Card',
    PAYMENT_STATUS PAYMENT_STATUS_TYPE DEFAULT 'Pending',
    SUBTOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    SHIPPING_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    DISCOUNT_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(3) DEFAULT 'RUB',
    SHIPPING_ADDRESS_ID UUID REFERENCES addresses(ID) ON DELETE SET NULL,
    BILLING_ADDRESS_ID UUID REFERENCES addresses(ID) ON DELETE SET NULL,
    NOTES TEXT,
    TRACKING_NUMBER VARCHAR(100),
    SHIPPED_DATE TIMESTAMP WITH TIME ZONE,
    DELIVERED_DATE TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_orders_ORDER_NUMBER ON orders(ORDER_NUMBER);
CREATE INDEX IDX_orders_CUSTOMER_ID ON orders(CUSTOMER_ID);
CREATE INDEX IDX_orders_ORDER_DATE ON orders(ORDER_DATE);
CREATE INDEX IDX_orders_STATUS ON orders(STATUS);

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ORDER_ID UUID NOT NULL REFERENCES orders(ID) ON DELETE CASCADE,
    PRODUCT_ID UUID NOT NULL REFERENCES products(ID) ON DELETE RESTRICT,
    QUANTITY INTEGER NOT NULL DEFAULT 1,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    TOTAL_PRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_order_items_ORDER_ID ON order_items(ORDER_ID);
CREATE INDEX IDX_order_items_PRODUCT_ID ON order_items(PRODUCT_ID);

-- Leads table
CREATE TABLE IF NOT EXISTS leads (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    LEAD_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    COMPANY_NAME VARCHAR(200),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(25),
    SOURCE VARCHAR(100),
    STATUS LEAD_STATUS_TYPE DEFAULT 'New',
    SCORE INTEGER DEFAULT 0,
    ASSIGNED_TO VARCHAR(100),
    NOTES TEXT,
    CONVERSION_DATE TIMESTAMP WITH TIME ZONE,
    CONVERTED_CUSTOMER_ID UUID REFERENCES customers(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_leads_LEAD_CODE ON leads(LEAD_CODE);
CREATE INDEX IDX_leads_STATUS ON leads(STATUS);
CREATE INDEX IDX_leads_EMAIL ON leads(EMAIL);
CREATE INDEX IDX_leads_ASSIGNED_TO ON leads(ASSIGNED_TO);

-- Deals table
CREATE TABLE IF NOT EXISTS deals (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    DEAL_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_ID UUID REFERENCES customers(ID) ON DELETE SET NULL,
    LEAD_ID UUID REFERENCES leads(ID) ON DELETE SET NULL,
    STAGE DEAL_STAGE_TYPE DEFAULT 'Prospecting',
    VALUE DECIMAL(12, 2) DEFAULT 0.00,
    CURRENCY VARCHAR(3) DEFAULT 'RUB',
    PROBABILITY INTEGER DEFAULT 50,
    EXPECTED_CLOSE_DATE DATE,
    ACTUAL_CLOSE_DATE DATE,
    ASSIGNED_TO VARCHAR(100),
    NOTES TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_deals_CUSTOMER_ID ON deals(CUSTOMER_ID);
CREATE INDEX IDX_deals_STAGE ON deals(STAGE);
CREATE INDEX IDX_deals_ASSIGNED_TO ON deals(ASSIGNED_TO);
CREATE INDEX IDX_deals_EXPECTED_CLOSE_DATE ON deals(EXPECTED_CLOSE_DATE);

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    CUSTOMER_ID UUID REFERENCES customers(ID) ON DELETE SET NULL,
    LEAD_ID UUID REFERENCES leads(ID) ON DELETE SET NULL,
    DEAL_ID UUID REFERENCES deals(ID) ON DELETE SET NULL,
    ASSIGNED_TO VARCHAR(100),
    STATUS TASK_STATUS_TYPE DEFAULT 'Not Started',
    PRIORITY PRIORITY_TYPE DEFAULT 'Medium',
    DUE_DATE TIMESTAMP WITH TIME ZONE,
    COMPLETED_DATE TIMESTAMP WITH TIME ZONE,
    ESTIMATED_HOURS DECIMAL(5, 2),
    ACTUAL_HOURS DECIMAL(5, 2),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_tasks_CUSTOMER_ID ON tasks(CUSTOMER_ID);
CREATE INDEX IDX_tasks_ASSIGNED_TO ON tasks(ASSIGNED_TO);
CREATE INDEX IDX_tasks_STATUS ON tasks(STATUS);
CREATE INDEX IDX_tasks_DUE_DATE ON tasks(DUE_DATE);

-- Invoices table
CREATE TABLE IF NOT EXISTS invoices (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    INVOICE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID UUID NOT NULL REFERENCES customers(ID) ON DELETE RESTRICT,
    ORDER_ID UUID REFERENCES orders(ID) ON DELETE SET NULL,
    DEAL_ID UUID REFERENCES deals(ID) ON DELETE SET NULL,
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS INVOICE_STATUS_TYPE DEFAULT 'Draft',
    SUBTOTAL DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    TAX_RATE DECIMAL(5, 2) DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(12, 2) DEFAULT 0.00,
    DISCOUNT_AMOUNT DECIMAL(12, 2) DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(3) DEFAULT 'RUB',
    NOTES TEXT,
    PAYMENT_DATE DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_invoices_INVOICE_NUMBER ON invoices(INVOICE_NUMBER);
CREATE INDEX IDX_invoices_CUSTOMER_ID ON invoices(CUSTOMER_ID);
CREATE INDEX IDX_invoices_STATUS ON invoices(STATUS);
CREATE INDEX IDX_invoices_DUE_DATE ON invoices(DUE_DATE);

-- Deliveries table
CREATE TABLE IF NOT EXISTS deliveries (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    DELIVERY_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    ORDER_ID UUID NOT NULL REFERENCES orders(ID) ON DELETE RESTRICT,
    CARRIER VARCHAR(100),
    TRACKING_NUMBER VARCHAR(100),
    STATUS DELIVERY_STATUS_TYPE DEFAULT 'Preparing',
    SHIPPING_DATE TIMESTAMP WITH TIME ZONE,
    EXPECTED_DELIVERY_DATE TIMESTAMP WITH TIME ZONE,
    ACTUAL_DELIVERY_DATE TIMESTAMP WITH TIME ZONE,
    DELIVERY_ADDRESS_ID UUID REFERENCES addresses(ID) ON DELETE SET NULL,
    RECIPIENT_NAME VARCHAR(200),
    RECIPIENT_PHONE VARCHAR(25),
    NOTES TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_deliveries_DELIVERY_NUMBER ON deliveries(DELIVERY_NUMBER);
CREATE INDEX IDX_deliveries_ORDER_ID ON deliveries(ORDER_ID);
CREATE INDEX IDX_deliveries_TRACKING_NUMBER ON deliveries(TRACKING_NUMBER);
CREATE INDEX IDX_deliveries_STATUS ON deliveries(STATUS);

-- Support Tickets table
CREATE TABLE IF NOT EXISTS support_tickets (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TICKET_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID UUID NOT NULL REFERENCES customers(ID) ON DELETE RESTRICT,
    SUBJECT VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    PRIORITY PRIORITY_TYPE DEFAULT 'Medium',
    STATUS TICKET_STATUS_TYPE DEFAULT 'Open',
    CATEGORY VARCHAR(100),
    ASSIGNED_TO VARCHAR(100),
    RESOLUTION TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_support_tickets_TICKET_NUMBER ON support_tickets(TICKET_NUMBER);
CREATE INDEX IDX_support_tickets_CUSTOMER_ID ON support_tickets(CUSTOMER_ID);
CREATE INDEX IDX_support_tickets_STATUS ON support_tickets(STATUS);
CREATE INDEX IDX_support_tickets_PRIORITY ON support_tickets(PRIORITY);
CREATE INDEX IDX_support_tickets_ASSIGNED_TO ON support_tickets(ASSIGNED_TO);

-- Create trigger functions for updating timestamps (PostgreSQL specific)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for all tables with UPDATED_AT column
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_addresses_updated_at BEFORE UPDATE ON addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_deals_updated_at BEFORE UPDATE ON deals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_invoices_updated_at BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_deliveries_updated_at BEFORE UPDATE ON deliveries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
