-- Comprehensive Customer Database Schema for PostgreSQL with UTF-8 encoding
-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Set database encoding to UTF8
SET client_encoding = 'UTF8';

-- Custom data types
CREATE TYPE CUSTOMER_STATUS_TYPE AS ENUM ('Active', 'Inactive', 'Suspended', 'Pending');
CREATE TYPE CUSTOMER_TYPE_ENUM AS ENUM ('Individual', 'Business', 'Enterprise', 'VIP');
CREATE TYPE GENDER_TYPE AS ENUM ('Male', 'Female', 'Other', 'Prefer not to say');
CREATE TYPE ADDRESS_TYPE AS ENUM ('Home', 'Work', 'Billing', 'Shipping', 'Other');
CREATE TYPE CONTACT_METHOD_TYPE AS ENUM ('Email', 'Phone', 'SMS', 'Mail');
CREATE TYPE CONTACT_FREQUENCY_TYPE AS ENUM ('Daily', 'Weekly', 'Monthly', 'Quarterly', 'Never');
CREATE TYPE COMPANY_SIZE_TYPE AS ENUM ('Startup', 'Small', 'Medium', 'Large', 'Enterprise');
CREATE TYPE ORDER_STATUS_TYPE AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded');
CREATE TYPE PAYMENT_METHOD_TYPE AS ENUM ('Credit Card', 'Debit Card', 'PayPal', 'Bank Transfer', 'Cash', 'Crypto');
CREATE TYPE PAYMENT_STATUS_TYPE AS ENUM ('Pending', 'Paid', 'Failed', 'Refunded', 'Partially Refunded');
CREATE TYPE INTERACTION_TYPE AS ENUM ('Email', 'Phone', 'Meeting', 'Chat', 'Support', 'Sale', 'Marketing', 'Other');
CREATE TYPE OUTCOME_TYPE AS ENUM ('Positive', 'Negative', 'Neutral', 'Follow-up Required');
CREATE TYPE PRIORITY_TYPE AS ENUM ('Low', 'Medium', 'High', 'Critical');
CREATE TYPE TICKET_STATUS_TYPE AS ENUM ('Open', 'In Progress', 'Resolved', 'Closed', 'Reopened');
CREATE TYPE DEAL_STAGE_TYPE AS ENUM ('Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost');
CREATE TYPE INVOICE_STATUS_TYPE AS ENUM ('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled');
CREATE TYPE DELIVERY_STATUS_TYPE AS ENUM ('Preparing', 'Shipped', 'In Transit', 'Delivered', 'Failed');
CREATE TYPE LEAD_STATUS_TYPE AS ENUM ('New', 'Contacted', 'Qualified', 'Disqualified', 'Converted');
CREATE TYPE TASK_STATUS_TYPE AS ENUM ('Not Started', 'In Progress', 'Completed', 'Deferred');


-- Customers table - main customer information
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_CODE VARCHAR(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(25),
    MOBILE VARCHAR(25),
    DATE_OF_BIRTH DATE,
    GENDER GENDER_TYPE DEFAULT 'Prefer not to say',
    REGISTRATION_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP WITH TIME ZONE,
    STATUS CUSTOMER_STATUS_TYPE DEFAULT 'Active',
    CUSTOMER_TYPE CUSTOMER_TYPE_ENUM DEFAULT 'Individual',
    PREFERRED_LANGUAGE VARCHAR(5) DEFAULT 'en',
    TIMEZONE VARCHAR(50) DEFAULT 'UTC',
    AVATAR_URL VARCHAR(255),
    NOTES TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Companies table - business customer information
CREATE TABLE IF NOT EXISTS COMPANIES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    COMPANY_NAME VARCHAR(200) NOT NULL,
    LEGAL_NAME VARCHAR(200),
    REGISTRATION_NUMBER VARCHAR(50),
    TAX_NUMBER VARCHAR(50),
    INDUSTRY VARCHAR(100),
    COMPANY_SIZE COMPANY_SIZE_TYPE DEFAULT 'Small',
    WEBSITE VARCHAR(255),
    FOUNDED_YEAR INTEGER CHECK (FOUNDED_YEAR > 1800 AND FOUNDED_YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    DESCRIPTION TEXT,
    ANNUAL_REVENUE NUMERIC(15,2),
    EMPLOYEE_COUNT INTEGER CHECK (EMPLOYEE_COUNT >= 0),
    LOGO_URL VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Customer company relationships
CREATE TABLE IF NOT EXISTS CUSTOMER_COMPANIES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID UUID NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    COMPANY_ID UUID NOT NULL REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    POSITION VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_CUSTOMER_COMPANY UNIQUE (CUSTOMER_ID, COMPANY_ID)
);

-- Addresses table
CREATE TABLE IF NOT EXISTS ADDRESSES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID UUID NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    ADDRESS_TYPE ADDRESS_TYPE DEFAULT 'Home',
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    APARTMENT VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Communication preferences
CREATE TABLE IF NOT EXISTS COMMUNICATION_PREFERENCES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID UUID NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    EMAIL_MARKETING BOOLEAN DEFAULT TRUE,
    SMS_MARKETING BOOLEAN DEFAULT FALSE,
    PHONE_CALLS BOOLEAN DEFAULT FALSE,
    PREFERRED_CONTACT_METHOD CONTACT_METHOD_TYPE DEFAULT 'Email',
    CONTACT_FREQUENCY CONTACT_FREQUENCY_TYPE DEFAULT 'Weekly',
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Products table
CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE NUMERIC(10, 2) NOT NULL,
    SKU VARCHAR(100) UNIQUE NOT NULL,
    STOCK_QUANTITY INT DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Orders table
CREATE TABLE IF NOT EXISTS ORDERS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID UUID NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    ORDER_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    STATUS ORDER_STATUS_TYPE DEFAULT 'Pending',
    TOTAL_AMOUNT NUMERIC(10, 2),
    SHIPPING_ADDRESS_ID UUID REFERENCES ADDRESSES(ID) ON DELETE SET NULL,
    BILLING_ADDRESS_ID UUID REFERENCES ADDRESSES(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Order Items table
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ORDER_ID UUID NOT NULL REFERENCES ORDERS(ID) ON DELETE CASCADE,
    PRODUCT_ID UUID NOT NULL REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    QUANTITY INT NOT NULL,
    UNIT_PRICE NUMERIC(10, 2) NOT NULL
);

-- Leads table
CREATE TABLE IF NOT EXISTS LEADS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(25),
    COMPANY_NAME VARCHAR(200),
    STATUS LEAD_STATUS_TYPE DEFAULT 'New',
    SOURCE VARCHAR(100),
    ASSIGNED_TO UUID REFERENCES CUSTOMERS(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tasks table
CREATE TABLE IF NOT EXISTS TASKS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DUE_DATE DATE,
    PRIORITY PRIORITY_TYPE DEFAULT 'Medium',
    STATUS TASK_STATUS_TYPE DEFAULT 'Not Started',
    ASSIGNED_TO UUID REFERENCES CUSTOMERS(ID) ON DELETE SET NULL,
    RELATED_TO_TYPE VARCHAR(50),
    RELATED_TO_ID UUID,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Deals table
CREATE TABLE IF NOT EXISTS DEALS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    DEAL_NAME VARCHAR(255) NOT NULL,
    COMPANY_ID UUID REFERENCES COMPANIES(ID) ON DELETE SET NULL,
    CONTACT_PERSON_ID UUID REFERENCES CUSTOMERS(ID) ON DELETE SET NULL,
    AMOUNT NUMERIC(12, 2),
    STAGE DEAL_STAGE_TYPE DEFAULT 'Prospecting',
    CLOSE_DATE DATE,
    ASSIGNED_TO UUID REFERENCES CUSTOMERS(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Invoices table
CREATE TABLE IF NOT EXISTS INVOICES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ORDER_ID UUID NOT NULL REFERENCES ORDERS(ID) ON DELETE CASCADE,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    TOTAL_AMOUNT NUMERIC(10, 2),
    STATUS INVOICE_STATUS_TYPE DEFAULT 'Draft',
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Deliveries table
CREATE TABLE IF NOT EXISTS DELIVERIES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ORDER_ID UUID NOT NULL REFERENCES ORDERS(ID) ON DELETE CASCADE,
    SHIPPING_DATE DATE,
    DELIVERY_DATE DATE,
    CARRIER VARCHAR(100),
    TRACKING_NUMBER VARCHAR(100),
    STATUS DELIVERY_STATUS_TYPE DEFAULT 'Preparing',
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_EMAIL ON CUSTOMERS(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_CUSTOMER_CODE ON CUSTOMERS(CUSTOMER_CODE);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_REGISTRATION_DATE ON CUSTOMERS(REGISTRATION_DATE);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_STATUS ON CUSTOMERS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_CUSTOMER_TYPE ON CUSTOMERS(CUSTOMER_TYPE);

CREATE INDEX IF NOT EXISTS IDX_COMPANIES_COMPANY_NAME ON COMPANIES(COMPANY_NAME);
CREATE INDEX IF NOT EXISTS IDX_COMPANIES_INDUSTRY ON COMPANIES(INDUSTRY);
CREATE INDEX IF NOT EXISTS IDX_COMPANIES_COMPANY_SIZE ON COMPANIES(COMPANY_SIZE);

CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_COMPANIES_CUSTOMER_ID ON CUSTOMER_COMPANIES(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_COMPANIES_COMPANY_ID ON CUSTOMER_COMPANIES(COMPANY_ID);

CREATE INDEX IF NOT EXISTS IDX_ADDRESSES_CUSTOMER_ID ON ADDRESSES(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_ADDRESSES_ADDRESS_TYPE ON ADDRESSES(ADDRESS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_ADDRESSES_COUNTRY ON ADDRESSES(COUNTRY);

CREATE INDEX IF NOT EXISTS IDX_ORDERS_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_ORDER_DATE ON ORDERS(ORDER_DATE);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS ON ORDERS(STATUS);

-- Create triggers for automatic updated_at timestamp updates
CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER UPDATE_CUSTOMERS_UPDATED_AT BEFORE UPDATE ON CUSTOMERS FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();
CREATE TRIGGER UPDATE_COMPANIES_UPDATED_AT BEFORE UPDATE ON COMPANIES FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();
CREATE TRIGGER UPDATE_ADDRESSES_UPDATED_AT BEFORE UPDATE ON ADDRESSES FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();
CREATE TRIGGER UPDATE_COMMUNICATION_PREFERENCES_UPDATED_AT BEFORE UPDATE ON COMMUNICATION_PREFERENCES FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();
CREATE TRIGGER UPDATE_ORDERS_UPDATED_AT BEFORE UPDATE ON ORDERS FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();
