-- Comprehensive Customer Database Schema for PostgreSQL with UTF-8 encoding
-- Table names: lowercase, Field names: UPPERCASE

-- Set connection encoding
SET client_encoding = 'UTF8';
SET timezone = 'UTC';

-- Customers table - main customer information
CREATE TABLE IF NOT EXISTS customers (
    "ID" SERIAL PRIMARY KEY,
    "CUSTOMER_CODE" VARCHAR(20) UNIQUE NOT NULL,
    "FIRST_NAME" VARCHAR(100) NOT NULL,
    "LAST_NAME" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(150) UNIQUE NOT NULL,
    "PHONE" VARCHAR(25),
    "MOBILE" VARCHAR(25),
    "DATE_OF_BIRTH" DATE,
    "GENDER" VARCHAR(20) DEFAULT 'Prefer not to say' CHECK ("GENDER" IN ('Male', 'Female', 'Other', 'Prefer not to say')),
    "REGISTRATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "LAST_LOGIN" TIMESTAMP,
    "STATUS" VARCHAR(20) DEFAULT 'Active' CHECK ("STATUS" IN ('Active', 'Inactive', 'Suspended', 'Pending')),
    "CUSTOMER_TYPE" VARCHAR(20) DEFAULT 'Individual' CHECK ("CUSTOMER_TYPE" IN ('Individual', 'Business', 'Enterprise', 'VIP')),
    "PREFERRED_LANGUAGE" VARCHAR(5) DEFAULT 'en',
    "TIMEZONE" VARCHAR(50) DEFAULT 'UTC',
    "AVATAR_URL" VARCHAR(255),
    "NOTES" TEXT,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customers_email ON customers("EMAIL");
CREATE INDEX IF NOT EXISTS idx_customers_customer_code ON customers("CUSTOMER_CODE");
CREATE INDEX IF NOT EXISTS idx_customers_registration_date ON customers("REGISTRATION_DATE");
CREATE INDEX IF NOT EXISTS idx_customers_status ON customers("STATUS");
CREATE INDEX IF NOT EXISTS idx_customers_customer_type ON customers("CUSTOMER_TYPE");

-- Companies table - business customer information
CREATE TABLE IF NOT EXISTS companies (
    "ID" SERIAL PRIMARY KEY,
    "COMPANY_NAME" VARCHAR(200) NOT NULL,
    "LEGAL_NAME" VARCHAR(200),
    "REGISTRATION_NUMBER" VARCHAR(50),
    "TAX_NUMBER" VARCHAR(50),
    "INDUSTRY" VARCHAR(100),
    "COMPANY_SIZE" VARCHAR(20) DEFAULT 'Small' CHECK ("COMPANY_SIZE" IN ('Startup', 'Small', 'Medium', 'Large', 'Enterprise')),
    "WEBSITE" VARCHAR(255),
    "FOUNDED_YEAR" INTEGER,
    "DESCRIPTION" TEXT,
    "ANNUAL_REVENUE" DECIMAL(15,2),
    "EMPLOYEE_COUNT" INTEGER,
    "LOGO_URL" VARCHAR(255),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_companies_company_name ON companies("COMPANY_NAME");
CREATE INDEX IF NOT EXISTS idx_companies_industry ON companies("INDUSTRY");
CREATE INDEX IF NOT EXISTS idx_companies_company_size ON companies("COMPANY_SIZE");

-- Customer-Company relationships
CREATE TABLE IF NOT EXISTS customer_companies (
    "ID" SERIAL PRIMARY KEY,
    "CUSTOMER_ID" INTEGER NOT NULL,
    "COMPANY_ID" INTEGER NOT NULL,
    "ROLE" VARCHAR(100),
    "START_DATE" DATE,
    "END_DATE" DATE,
    "IS_PRIMARY" BOOLEAN DEFAULT FALSE,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CUSTOMER_ID") REFERENCES customers("ID") ON DELETE CASCADE,
    FOREIGN KEY ("COMPANY_ID") REFERENCES companies("ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_customer_companies_customer_id ON customer_companies("CUSTOMER_ID");
CREATE INDEX IF NOT EXISTS idx_customer_companies_company_id ON customer_companies("COMPANY_ID");

-- Addresses table
CREATE TABLE IF NOT EXISTS addresses (
    "ID" SERIAL PRIMARY KEY,
    "CUSTOMER_ID" INTEGER,
    "COMPANY_ID" INTEGER,
    "ADDRESS_TYPE" VARCHAR(20) DEFAULT 'Other' CHECK ("ADDRESS_TYPE" IN ('Home', 'Work', 'Billing', 'Shipping', 'Other')),
    "STREET_ADDRESS" VARCHAR(255) NOT NULL,
    "APARTMENT" VARCHAR(50),
    "CITY" VARCHAR(100) NOT NULL,
    "STATE_PROVINCE" VARCHAR(100),
    "POSTAL_CODE" VARCHAR(20),
    "COUNTRY" VARCHAR(100) NOT NULL DEFAULT 'Russia',
    "LATITUDE" DECIMAL(10, 8),
    "LONGITUDE" DECIMAL(11, 8),
    "IS_DEFAULT" BOOLEAN DEFAULT FALSE,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CUSTOMER_ID") REFERENCES customers("ID") ON DELETE CASCADE,
    FOREIGN KEY ("COMPANY_ID") REFERENCES companies("ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_addresses_customer_id ON addresses("CUSTOMER_ID");
CREATE INDEX IF NOT EXISTS idx_addresses_company_id ON addresses("COMPANY_ID");
CREATE INDEX IF NOT EXISTS idx_addresses_address_type ON addresses("ADDRESS_TYPE");

-- Products table
CREATE TABLE IF NOT EXISTS products (
    "ID" SERIAL PRIMARY KEY,
    "PRODUCT_CODE" VARCHAR(50) UNIQUE NOT NULL,
    "NAME" VARCHAR(200) NOT NULL,
    "DESCRIPTION" TEXT,
    "CATEGORY" VARCHAR(100),
    "SUBCATEGORY" VARCHAR(100),
    "BRAND" VARCHAR(100),
    "PRICE" DECIMAL(10, 2) NOT NULL,
    "COST" DECIMAL(10, 2),
    "WEIGHT" DECIMAL(8, 3),
    "DIMENSIONS" VARCHAR(100),
    "COLOR" VARCHAR(50),
    "SIZE" VARCHAR(50),
    "MATERIAL" VARCHAR(100),
    "STOCK_QUANTITY" INTEGER DEFAULT 0,
    "MIN_STOCK_LEVEL" INTEGER DEFAULT 0,
    "IS_ACTIVE" BOOLEAN DEFAULT TRUE,
    "IMAGE_URL" VARCHAR(255),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_product_code ON products("PRODUCT_CODE");
CREATE INDEX IF NOT EXISTS idx_products_category ON products("CATEGORY");
CREATE INDEX IF NOT EXISTS idx_products_brand ON products("BRAND");
CREATE INDEX IF NOT EXISTS idx_products_active ON products("IS_ACTIVE");

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    "ID" SERIAL PRIMARY KEY,
    "ORDER_NUMBER" VARCHAR(50) UNIQUE NOT NULL,
    "CUSTOMER_ID" INTEGER NOT NULL,
    "ORDER_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "STATUS" VARCHAR(20) DEFAULT 'Pending' CHECK ("STATUS" IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded')),
    "PAYMENT_METHOD" VARCHAR(20) DEFAULT 'Credit Card' CHECK ("PAYMENT_METHOD" IN ('Credit Card', 'Debit Card', 'PayPal', 'Bank Transfer', 'Cash', 'Crypto')),
    "PAYMENT_STATUS" VARCHAR(20) DEFAULT 'Pending' CHECK ("PAYMENT_STATUS" IN ('Pending', 'Paid', 'Failed', 'Refunded', 'Partially Refunded')),
    "SUBTOTAL" DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    "TAX_AMOUNT" DECIMAL(10, 2) DEFAULT 0.00,
    "SHIPPING_AMOUNT" DECIMAL(10, 2) DEFAULT 0.00,
    "DISCOUNT_AMOUNT" DECIMAL(10, 2) DEFAULT 0.00,
    "TOTAL_AMOUNT" DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    "CURRENCY" VARCHAR(3) DEFAULT 'RUB',
    "SHIPPING_ADDRESS_ID" INTEGER,
    "BILLING_ADDRESS_ID" INTEGER,
    "NOTES" TEXT,
    "TRACKING_NUMBER" VARCHAR(100),
    "SHIPPED_DATE" TIMESTAMP,
    "DELIVERED_DATE" TIMESTAMP,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CUSTOMER_ID") REFERENCES customers("ID") ON DELETE RESTRICT,
    FOREIGN KEY ("SHIPPING_ADDRESS_ID") REFERENCES addresses("ID") ON DELETE SET NULL,
    FOREIGN KEY ("BILLING_ADDRESS_ID") REFERENCES addresses("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders("ORDER_NUMBER");
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders("CUSTOMER_ID");
CREATE INDEX IF NOT EXISTS idx_orders_order_date ON orders("ORDER_DATE");
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders("STATUS");

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    "ID" SERIAL PRIMARY KEY,
    "ORDER_ID" INTEGER NOT NULL,
    "PRODUCT_ID" INTEGER NOT NULL,
    "QUANTITY" INTEGER NOT NULL DEFAULT 1,
    "UNIT_PRICE" DECIMAL(10, 2) NOT NULL,
    "TOTAL_PRICE" DECIMAL(10, 2) NOT NULL,
    "DISCOUNT_AMOUNT" DECIMAL(10, 2) DEFAULT 0.00,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("ORDER_ID") REFERENCES orders("ID") ON DELETE CASCADE,
    FOREIGN KEY ("PRODUCT_ID") REFERENCES products("ID") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items("ORDER_ID");
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items("PRODUCT_ID");

-- Leads table
CREATE TABLE IF NOT EXISTS leads (
    "ID" SERIAL PRIMARY KEY,
    "LEAD_CODE" VARCHAR(20) UNIQUE NOT NULL,
    "FIRST_NAME" VARCHAR(100),
    "LAST_NAME" VARCHAR(100),
    "COMPANY_NAME" VARCHAR(200),
    "EMAIL" VARCHAR(150),
    "PHONE" VARCHAR(25),
    "SOURCE" VARCHAR(100),
    "STATUS" VARCHAR(20) DEFAULT 'New' CHECK ("STATUS" IN ('New', 'Contacted', 'Qualified', 'Disqualified', 'Converted')),
    "SCORE" INTEGER DEFAULT 0,
    "ASSIGNED_TO" VARCHAR(100),
    "NOTES" TEXT,
    "CONVERSION_DATE" TIMESTAMP,
    "CONVERTED_CUSTOMER_ID" INTEGER,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CONVERTED_CUSTOMER_ID") REFERENCES customers("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_leads_lead_code ON leads("LEAD_CODE");
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads("STATUS");
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads("EMAIL");
CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads("ASSIGNED_TO");

-- Deals table
CREATE TABLE IF NOT EXISTS deals (
    "ID" SERIAL PRIMARY KEY,
    "DEAL_NAME" VARCHAR(200) NOT NULL,
    "CUSTOMER_ID" INTEGER,
    "LEAD_ID" INTEGER,
    "STAGE" VARCHAR(20) DEFAULT 'Prospecting' CHECK ("STAGE" IN ('Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost')),
    "VALUE" DECIMAL(12, 2) DEFAULT 0.00,
    "CURRENCY" VARCHAR(3) DEFAULT 'RUB',
    "PROBABILITY" INTEGER DEFAULT 50,
    "EXPECTED_CLOSE_DATE" DATE,
    "ACTUAL_CLOSE_DATE" DATE,
    "ASSIGNED_TO" VARCHAR(100),
    "NOTES" TEXT,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CUSTOMER_ID") REFERENCES customers("ID") ON DELETE SET NULL,
    FOREIGN KEY ("LEAD_ID") REFERENCES leads("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_deals_customer_id ON deals("CUSTOMER_ID");
CREATE INDEX IF NOT EXISTS idx_deals_stage ON deals("STAGE");
CREATE INDEX IF NOT EXISTS idx_deals_assigned_to ON deals("ASSIGNED_TO");
CREATE INDEX IF NOT EXISTS idx_deals_expected_close_date ON deals("EXPECTED_CLOSE_DATE");

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    "ID" SERIAL PRIMARY KEY,
    "TITLE" VARCHAR(200) NOT NULL,
    "DESCRIPTION" TEXT,
    "CUSTOMER_ID" INTEGER,
    "LEAD_ID" INTEGER,
    "DEAL_ID" INTEGER,
    "ASSIGNED_TO" VARCHAR(100),
    "STATUS" VARCHAR(20) DEFAULT 'Not Started' CHECK ("STATUS" IN ('Not Started', 'In Progress', 'Completed', 'Deferred')),
    "PRIORITY" VARCHAR(20) DEFAULT 'Medium' CHECK ("PRIORITY" IN ('Low', 'Medium', 'High', 'Critical')),
    "DUE_DATE" TIMESTAMP,
    "COMPLETED_DATE" TIMESTAMP,
    "ESTIMATED_HOURS" DECIMAL(5, 2),
    "ACTUAL_HOURS" DECIMAL(5, 2),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CUSTOMER_ID") REFERENCES customers("ID") ON DELETE SET NULL,
    FOREIGN KEY ("LEAD_ID") REFERENCES leads("ID") ON DELETE SET NULL,
    FOREIGN KEY ("DEAL_ID") REFERENCES deals("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_customer_id ON tasks("CUSTOMER_ID");
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks("ASSIGNED_TO");
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks("STATUS");
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks("DUE_DATE");

-- Invoices table
CREATE TABLE IF NOT EXISTS invoices (
    "ID" SERIAL PRIMARY KEY,
    "INVOICE_NUMBER" VARCHAR(50) UNIQUE NOT NULL,
    "CUSTOMER_ID" INTEGER NOT NULL,
    "ORDER_ID" INTEGER,
    "DEAL_ID" INTEGER,
    "INVOICE_DATE" DATE NOT NULL,
    "DUE_DATE" DATE NOT NULL,
    "STATUS" VARCHAR(20) DEFAULT 'Draft' CHECK ("STATUS" IN ('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled')),
    "SUBTOTAL" DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    "TAX_RATE" DECIMAL(5, 2) DEFAULT 0.00,
    "TAX_AMOUNT" DECIMAL(12, 2) DEFAULT 0.00,
    "DISCOUNT_AMOUNT" DECIMAL(12, 2) DEFAULT 0.00,
    "TOTAL_AMOUNT" DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    "CURRENCY" VARCHAR(3) DEFAULT 'RUB',
    "NOTES" TEXT,
    "PAYMENT_DATE" DATE,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("CUSTOMER_ID") REFERENCES customers("ID") ON DELETE RESTRICT,
    FOREIGN KEY ("ORDER_ID") REFERENCES orders("ID") ON DELETE SET NULL,
    FOREIGN KEY ("DEAL_ID") REFERENCES deals("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_invoices_invoice_number ON invoices("INVOICE_NUMBER");
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON invoices("CUSTOMER_ID");
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices("STATUS");
CREATE INDEX IF NOT EXISTS idx_invoices_due_date ON invoices("DUE_DATE");

-- Deliveries table
CREATE TABLE IF NOT EXISTS deliveries (
    "ID" SERIAL PRIMARY KEY,
    "DELIVERY_NUMBER" VARCHAR(50) UNIQUE NOT NULL,
    "ORDER_ID" INTEGER NOT NULL,
    "CARRIER" VARCHAR(100),
    "TRACKING_NUMBER" VARCHAR(100),
    "STATUS" VARCHAR(20) DEFAULT 'Preparing' CHECK ("STATUS" IN ('Preparing', 'Shipped', 'In Transit', 'Delivered', 'Failed')),
    "SHIPPING_DATE" TIMESTAMP,
    "EXPECTED_DELIVERY_DATE" TIMESTAMP,
    "ACTUAL_DELIVERY_DATE" TIMESTAMP,
    "DELIVERY_ADDRESS_ID" INTEGER,
    "RECIPIENT_NAME" VARCHAR(200),
    "RECIPIENT_PHONE" VARCHAR(25),
    "NOTES" TEXT,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("ORDER_ID") REFERENCES orders("ID") ON DELETE RESTRICT,
    FOREIGN KEY ("DELIVERY_ADDRESS_ID") REFERENCES addresses("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_deliveries_delivery_number ON deliveries("DELIVERY_NUMBER");
CREATE INDEX IF NOT EXISTS idx_deliveries_order_id ON deliveries("ORDER_ID");
CREATE INDEX IF NOT EXISTS idx_deliveries_tracking_number ON deliveries("TRACKING_NUMBER");
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON deliveries("STATUS");

-- Create function to update UPDATED_AT timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."UPDATED_AT" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for UPDATED_AT field
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON customers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_addresses_updated_at BEFORE UPDATE ON addresses
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_deals_updated_at BEFORE UPDATE ON deals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_invoices_updated_at BEFORE UPDATE ON invoices
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_deliveries_updated_at BEFORE UPDATE ON deliveries
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
